export const spriteCells = Object.freeze({
  stone: [0, 0],
  moss: [1, 0],
  water: [2, 0],
  bridge: [3, 0],
  wall: [0, 1],
  pillar: [1, 1],
  gate: [2, 1],
  rune: [3, 1],
  crystal: [0, 2],
  thorn: [1, 2],
  mirror: [2, 2],
  beacon: [3, 2],
  terminal: [0, 3],
  stair: [1, 3],
  vine: [2, 3],
  chest: [3, 3],
});

const block = (type, col, row, size = 1, activatesAt = Infinity) => ({
  type,
  col,
  row,
  size,
  activatesAt,
});

export const exercises = [
  {
    id: "rune-column",
    skill: "Visual Block",
    language: "typescript",
    title: "Light all four runes in one spell.",
    instruction: "The four feature marks form a column—not four separate edits.",
    initialCode: [
      "const north = false; // [ ]",
      "const east  = false; // [ ]",
      "const south = false; // [ ]",
      "const west  = false; // [ ]",
    ],
    targetCode: [
      "const north = false; // [x]",
      "const east  = false; // [x]",
      "const south = false; // [x]",
      "const west  = false; // [x]",
    ],
    cursor: [0, 25],
    solution: ["Ctrl-v", "3", "j", "r", "x"],
    hints: [
      { keys: "Ctrl-v", label: "enter block mode" },
      { keys: "3j", label: "reach three rows" },
      { keys: "rx", label: "replace with x" },
    ],
    checkpoints: [
      { at: 1, mode: "V-Block", cursor: [0, 25], selection: { kind: "block", from: [0, 25], to: [0, 25] } },
      { at: 3, mode: "V-Block", cursor: [3, 25], selection: { kind: "block", from: [0, 25], to: [3, 25] } },
      { at: 5, mode: "Complete", code: "target", cursor: [3, 25] },
    ],
    scene: {
      theme: "moonroot",
      template: "causeway",
      codeSide: "left",
      successEffect: "gate-open",
      blocks: [
        block("gate", 10, 1, 2, 5),
        block("rune", 10, 4, 1, 2),
        block("rune", 10, 5, 1, 3),
        block("rune", 10, 6, 1, 4),
        block("rune", 10, 7, 1, 5),
      ],
    },
  },
  {
    id: "crystal-string",
    skill: "Text Object · Quotes",
    language: "typescript",
    title: "Retune the environment crystal.",
    instruction: "Change only the text inside the quotes to production.",
    initialCode: ['const env = "development";'],
    targetCode: ['const env = "production";'],
    cursor: [0, 15],
    solution: ["c", "i", '"', "p", "r", "o", "d", "u", "c", "t", "i", "o", "n", "Escape"],
    hints: [
      { keys: 'ci"', label: "change inside quotes" },
      { keys: "production", label: "write the new value" },
      { keys: "Esc", label: "return to Normal" },
    ],
    checkpoints: [
      { at: 3, mode: "Insert", selection: { kind: "linear", from: [0, 13], to: [0, 23] } },
      { at: 13, mode: "Insert", code: "target", cursor: [0, 22] },
      { at: 14, mode: "Complete", code: "target" },
    ],
    scene: {
      theme: "glass",
      template: "islands",
      codeSide: "right",
      successEffect: "crystal-charge",
      blocks: [block("crystal", 2, 3, 2, 14), block("pillar", 2, 6, 1)],
    },
  },
  {
    id: "empty-altar",
    skill: "Text Object · Parentheses",
    language: "javascript",
    title: "Clear the altar in one motion.",
    instruction: "Remove everything inside renderCard’s parentheses.",
    initialCode: ["renderCard(user, theme, debug);"],
    targetCode: ["renderCard();"],
    cursor: [0, 16],
    solution: ["d", "i", "("],
    hints: [
      { keys: "d", label: "delete operator" },
      { keys: "i(", label: "inside parentheses" },
    ],
    checkpoints: [
      { at: 2, mode: "Operator", selection: { kind: "linear", from: [0, 11], to: [0, 28] } },
      { at: 3, mode: "Complete", code: "target" },
    ],
    scene: {
      theme: "deepwater",
      template: "altar",
      codeSide: "left",
      successEffect: "altar-clear",
      blocks: [
        block("rune", 10, 4, 1, 3),
        block("crystal", 9, 6, 1, 3),
        block("crystal", 11, 6, 1, 3),
      ],
    },
  },
  {
    id: "debug-thorns",
    skill: "Count + Delete",
    language: "javascript",
    title: "Cut three debug thorns at once.",
    instruction: "Remove the three debug lines and leave the return untouched.",
    initialCode: [
      'debug("cache");',
      'debug("auth");',
      'debug("router");',
      "return app.start();",
    ],
    targetCode: ["return app.start();"],
    cursor: [0, 0],
    solution: ["3", "d", "d"],
    hints: [
      { keys: "3", label: "count three lines" },
      { keys: "dd", label: "delete whole lines" },
    ],
    checkpoints: [
      { at: 1, mode: "Count: 3", selection: { kind: "line", from: [0, 0], to: [2, 15] } },
      { at: 3, mode: "Complete", code: "target" },
    ],
    scene: {
      theme: "ember",
      template: "lanes",
      codeSide: "right",
      successEffect: "thorns-clear",
      blocks: [
        block("thorn", 2, 3, 1, 3),
        block("thorn", 2, 5, 1, 3),
        block("thorn", 2, 7, 1, 3),
      ],
    },
  },
  {
    id: "mirror-repeat",
    skill: "Dot Repeat",
    language: "javascript",
    title: "Teach the mirrors one change.",
    instruction: "Change old to new once, then repeat the edit twice.",
    initialCode: [
      "cache.old = loader;",
      "auth.old  = verifier;",
      "api.old   = router;",
    ],
    targetCode: [
      "cache.new = loader;",
      "auth.new  = verifier;",
      "api.new   = router;",
    ],
    cursor: [0, 7],
    solution: ["c", "i", "w", "n", "e", "w", "Escape", "j", ".", "j", "."],
    hints: [
      { keys: "ciwnew", label: "change the first word" },
      { keys: "Esc", label: "finish the edit" },
      { keys: "j.j.", label: "move and repeat" },
    ],
    checkpoints: [
      { at: 3, mode: "Insert", selection: { kind: "linear", from: [0, 6], to: [0, 8] } },
      { at: 7, mode: "Normal", code: ["cache.new = loader;", "auth.old  = verifier;", "api.old   = router;"], cursor: [0, 8] },
      { at: 8, mode: "Normal", cursor: [1, 8] },
      { at: 9, mode: "Normal", code: ["cache.new = loader;", "auth.new  = verifier;", "api.old   = router;"], cursor: [1, 8] },
      { at: 10, mode: "Normal", cursor: [2, 8] },
      { at: 11, mode: "Complete", code: "target", cursor: [2, 8] },
    ],
    scene: {
      theme: "glass",
      template: "mirrors",
      codeSide: "left",
      successEffect: "mirrors-turn",
      blocks: [
        block("mirror", 10, 3, 1, 7),
        block("mirror", 10, 5, 1, 9),
        block("mirror", 10, 7, 1, 11),
      ],
    },
  },
  {
    id: "beacon-macro",
    skill: "Macro",
    language: "javascript",
    title: "Record one silence spell.",
    instruction: "Comment the first API call, then replay the macro twice.",
    initialCode: ["fetchUser();", "fetchTeam();", "fetchAdmin();"],
    targetCode: ["// fetchUser();", "// fetchTeam();", "// fetchAdmin();"],
    cursor: [0, 0],
    solution: ["q", "a", "I", "/", "/", " ", "Escape", "q", "j", "@", "a", "j", "@", "@"],
    hints: [
      { keys: "qa…q", label: "record into register a" },
      { keys: "I// ", label: "comment from line start" },
      { keys: "@a · @@", label: "play and repeat" },
    ],
    checkpoints: [
      { at: 2, mode: "Recording @a" },
      { at: 7, mode: "Recording @a", code: ["// fetchUser();", "fetchTeam();", "fetchAdmin();"] },
      { at: 8, mode: "Normal", code: ["// fetchUser();", "fetchTeam();", "fetchAdmin();"], cursor: [0, 2] },
      { at: 9, mode: "Normal", cursor: [1, 2] },
      { at: 11, mode: "Normal", code: ["// fetchUser();", "// fetchTeam();", "fetchAdmin();"], cursor: [1, 2] },
      { at: 12, mode: "Normal", cursor: [2, 2] },
      { at: 14, mode: "Complete", code: "target", cursor: [2, 2] },
    ],
    scene: {
      theme: "ember",
      template: "beacons",
      codeSide: "right",
      successEffect: "beacons-light",
      blocks: [
        block("beacon", 2, 3, 1, 7),
        block("beacon", 2, 5, 1, 11),
        block("beacon", 2, 7, 1, 14),
      ],
    },
  },
  {
    id: "terminal-substitute",
    skill: "Substitute",
    language: "javascript",
    title: "Rewrite every old declaration.",
    instruction: "Use one Ex command to replace var with const everywhere.",
    initialCode: [
      "var port = 3000;",
      'var host = "localhost";',
      "var secure = false;",
    ],
    targetCode: [
      "const port = 3000;",
      'const host = "localhost";',
      "const secure = false;",
    ],
    cursor: [0, 0],
    solution: [":", "%", "s", "/", "v", "a", "r", "/", "c", "o", "n", "s", "t", "/", "g", "Enter"],
    hints: [
      { keys: ":%s", label: "substitute all lines" },
      { keys: "/var/const/g", label: "old, new, globally" },
      { keys: "Enter", label: "run the command" },
    ],
    checkpoints: [
      { at: 1, mode: "Command" },
      { at: 15, mode: "Command" },
      { at: 16, mode: "Complete", code: "target" },
    ],
    scene: {
      theme: "deepwater",
      template: "terminal",
      codeSide: "right",
      successEffect: "terminal-run",
      blocks: [block("terminal", 1, 3, 2, 16), block("pillar", 2, 7, 1)],
    },
  },
  {
    id: "bridge-indent",
    skill: "Visual Line",
    language: "javascript",
    title: "Set the bridge lines straight.",
    instruction: "Select both statements and indent them together.",
    initialCode: ["if (ready) {", "send();", "notify();", "}"],
    targetCode: ["if (ready) {", "  send();", "  notify();", "}"],
    cursor: [1, 0],
    solution: ["V", "j", ">"],
    hints: [
      { keys: "V", label: "select the whole line" },
      { keys: "j", label: "include the next line" },
      { keys: ">", label: "indent selection" },
    ],
    checkpoints: [
      { at: 1, mode: "Visual Line", cursor: [1, 0], selection: { kind: "line", from: [1, 0], to: [1, 6] } },
      { at: 2, mode: "Visual Line", cursor: [2, 0], selection: { kind: "line", from: [1, 0], to: [2, 8] } },
      { at: 3, mode: "Complete", code: "target", cursor: [2, 0] },
    ],
    scene: {
      theme: "moonroot",
      template: "bridge",
      codeSide: "left",
      successEffect: "bridge-align",
      blocks: [block("stair", 10, 4, 1, 2), block("stair", 10, 6, 1, 3)],
    },
  },
  {
    id: "join-aqueduct",
    skill: "Join Lines",
    language: "javascript",
    title: "Reconnect the broken statement.",
    instruction: "Join the two source lines with one uppercase command.",
    initialCode: ["const label =", "  user.name;"],
    targetCode: ["const label = user.name;"],
    cursor: [0, 0],
    solution: ["J"],
    hints: [{ keys: "J", label: "join with the next line" }],
    checkpoints: [{ at: 1, mode: "Complete", code: "target" }],
    scene: {
      theme: "deepwater",
      template: "aqueduct",
      codeSide: "right",
      successEffect: "bridge-align",
      blocks: [block("bridge", 2, 4, 1, 1), block("bridge", 2, 6, 1, 1)],
    },
  },
  {
    id: "cut-vine",
    skill: "Find + Till",
    language: "javascript",
    title: "Cut the draft suffix cleanly.",
    instruction: "Find the hyphen, then delete until the closing quote.",
    initialCode: ['const slug = "draft-post";'],
    targetCode: ['const slug = "draft";'],
    cursor: [0, 0],
    solution: ["f", "-", "d", "t", '"'],
    hints: [
      { keys: "f-", label: "find the hyphen" },
      { keys: 'dt"', label: "delete until quote" },
    ],
    checkpoints: [
      { at: 2, mode: "Normal", cursor: [0, 19] },
      { at: 4, mode: "Operator", selection: { kind: "linear", from: [0, 19], to: [0, 23] } },
      { at: 5, mode: "Complete", code: "target" },
    ],
    scene: {
      theme: "glass",
      template: "vines",
      codeSide: "left",
      successEffect: "vine-cut",
      blocks: [block("vine", 10, 3, 2, 5), block("crystal", 10, 7, 1, 5)],
    },
  },
  {
    id: "echo-test",
    skill: "Yank + Put",
    language: "javascript",
    title: "Echo the test into a twin.",
    instruction: "Yank the complete test line and put a copy beneath it.",
    initialCode: ['test("save", () => ok(save()));'],
    targetCode: [
      'test("save", () => ok(save()));',
      'test("save", () => ok(save()));',
    ],
    cursor: [0, 0],
    solution: ["y", "y", "p"],
    hints: [
      { keys: "yy", label: "yank the whole line" },
      { keys: "p", label: "put it below" },
    ],
    checkpoints: [
      { at: 2, mode: "Yanked 1 line" },
      { at: 3, mode: "Complete", code: "target" },
    ],
    scene: {
      theme: "ember",
      template: "echo",
      codeSide: "right",
      successEffect: "chest-echo",
      blocks: [block("chest", 2, 4, 1), block("chest", 2, 6, 1, 3)],
    },
  },
];

export const knownThemes = Object.freeze(["moonroot", "ember", "glass", "deepwater"]);
export const knownTemplates = Object.freeze([
  "causeway",
  "islands",
  "altar",
  "lanes",
  "mirrors",
  "beacons",
  "terminal",
  "bridge",
  "aqueduct",
  "vines",
  "echo",
]);
