/* Report: renders the audit's JSON as a Markdown summary for review. */

const VERDICTS = ["shorter", "justified", "engine-mismatch", "host-mismatch", "inconclusive", "none-shorter", "trivial"];

const code = keys => `\`${keys.map(key => (key === "Escape" ? "<Esc>" : key === "Enter" ? "<CR>" : key)).join(" ")}\``;

function table(headers, rows) {
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map(row => `| ${row.join(" | ")} |`),
  ].join("\n");
}

function rejection(route) {
  if (!route) return "";
  return route.freshEditor
    ? `${code(route.keys)} reaches the target in the app's adapter and not in native Vim`
    : `${code(route.keys)} reached the target in the search's editor and not in a fresh one`;
}

export function renderMarkdown(report) {
  const exercises = report.exercises.filter(Boolean);
  const byVerdict = verdict => exercises.filter(exercise => exercise.verdict === verdict);
  const units = [...new Set(exercises.map(exercise => exercise.unitNumber))].sort((left, right) => left - right);
  const lines = [
    "# Route audit",
    "",
    "Generated by `npm run audit:routes`. Do not edit by hand.",
    "",
    "For every exercise the audit searches for a route shorter than the taught one, using only commands the course has",
    "used in a demo or exercise before it (plus the exercise's own), and replays every candidate in the app's Vim",
    "adapter. A route it reports also reaches the target in native Vim.",
    "",
    "- **shorter**: a route with fewer keys exists. This flags the exercise for review: re-author it if a small",
    "  buffer can show the command doing real work, or record in `verification.routeNote` why it stays as it is.",
    "- **justified**: shorter routes exist, and the exercise's `routeNote` records the review and why it teaches the",
    "  longer one.",
    `- **counted** routes need a count of ${report.countedFrom} or more. They are listed but do not beat the canonical.`,
    "- **none-shorter**: the search covered every route cheaper than the canonical.",
    "- **inconclusive**: the budget ran out first; **searched** says how far the search got. This is not a flag.",
    "- **engine-mismatch**: the app's adapter and native Vim disagree about the shorter route.",
    "- **host-mismatch**: the canonical does not reach the target inside the audit; results are not trusted.",
    "- **trivial**: the start already matches the target, so the target does not check what the taught keys change",
    "  (usually a register). The exercise completes only because the lesson also requires every scripted key.",
    "",
    "What the search tries, and so what \"none-shorter\" speaks for:",
    "",
    `- at most ${report.extraEdits ?? 1} more text-changing command than the canonical makes, and at most one that moves the`,
    "  text away from the target, only when the canonical does so too;",
    "- typed text from the canonical's own insert runs and the difference between initial and target lines;",
    "- Ex lines from the canonical only; searches for words in the buffer and their first one to three letters;",
    "- counts 2–9 on word and line motions, 2–3 on character finds; a line number before `G` is free when that line is",
    "  on screen at the start, and counted when a fixed viewport hides it;",
    "- charwise and linewise Visual selections only in exercises that use them, with one motion or text object;",
    "- window motions and scrolls (`H` `M` `L`, `Ctrl-f` and the rest, `zt` `zz` `zb`) only where the exercise fixes the",
    "  viewport;",
    "- commands that make a change the target does not need (case, indent, increments, joins, puts) are not offered.",
    "",
    "It does not try macros, marks, undo, or Insert-mode controls. **covered** says whether the canonical itself can be",
    "spelled from the offered commands; when it cannot, a none-shorter verdict speaks only for what the grammar covers.",
    "",
    "Two prunings keep the search inside its budget without changing what it covers. Commands that differ only in a",
    "motion that lands in the same place (an operator and two motions of the same kind, or two Visual selections) are",
    "replayed once. An edit that may not move the text away from the target is replayed only if it can change a line",
    "that still differs. States are told apart by the text, cursor, mode, checked registers, the viewport where it is",
    "fixed, and what `;`, `n`, `.`, `&`, `@:`, and a run of `j` would do next. When native Vim rejects a route, the",
    "other spellings that tied with it in the search are tried before the verdict becomes engine-mismatch.",
    "",
    "An inconclusive exercise's **searched** column reads, for example, `3 of 12`: every route of up to 3 keys was",
    "tried, and a shorter route could have up to 12. When the full search is inconclusive, a second, deeper search",
    "tries only the core commands (line and word motions, operators, standalone edits, typed text, and the canonical's",
    "own Ex lines, with counts up to 3). Any route it finds is reported like any other; finding none proves nothing.",
    "",
    `Budget: ${report.budget.maxEvaluations} states or ${report.budget.secondsPerExercise}s per exercise`
      + (report.budget.probeSecondsPerExercise ? `, then ${report.budget.probeSecondsPerExercise}s for the core search.` : "."),
    "",
    "## Summary",
    "",
    table(
      ["Unit", ...VERDICTS, "counted"],
      units.map(unit => {
        const inUnit = exercises.filter(exercise => exercise.unitNumber === unit);
        return [String(unit), ...VERDICTS.map(verdict => String(inUnit.filter(exercise => exercise.verdict === verdict).length)),
          String(inUnit.filter(exercise => exercise.counted?.length).length)];
      }),
    ),
    "",
    table(
      ["Phase", ...VERDICTS],
      ["isolate", "mix", "challenge"].map(phase => [phase, ...VERDICTS.map(verdict => String(exercises.filter(exercise => exercise.phase === phase && exercise.verdict === verdict).length))]),
    ),
    "",
  ];

  const flagged = [...byVerdict("shorter")].sort((left, right) => (right.canonical.cost - right.routes[0].cost) - (left.canonical.cost - left.routes[0].cost));
  lines.push("## Shorter routes", "");
  lines.push(flagged.length
    ? table(["Unit", "Exercise", "Phase", "Taught", "Keys", "Shorter", "Keys", "Saves"], flagged.map(exercise => {
      const best = exercise.routes[0];
      return [String(exercise.unitNumber), exercise.id, exercise.phase, code(exercise.canonical.keys), String(exercise.canonical.cost),
        code(best.keys), String(best.cost), String(exercise.canonical.cost - best.cost)];
    }))
    : "None.");
  lines.push("");

  for (const [title, verdict] of [["Justified", "justified"], ["Targets that check nothing", "trivial"], ["Engine mismatches", "engine-mismatch"], ["Host mismatches", "host-mismatch"], ["Inconclusive", "inconclusive"]]) {
    const rows = byVerdict(verdict);
    if (!rows.length) continue;
    lines.push(`## ${title}`, "");
    const searched = exercise => (verdict === "inconclusive"
      ? `${exercise.reachedCost ?? 0} of ${exercise.canonical.cost - 1}`
      : String(exercise.reachedCost ?? ""));
    lines.push(table(["Unit", "Exercise", "Phase", "Keys", verdict === "inconclusive" ? "Searched" : "Reached", "Note"], rows.map(exercise => [
      String(exercise.unitNumber), exercise.id, exercise.phase, String(exercise.canonical.cost),
      searched(exercise), exercise.routeNote || (exercise.routes?.[0] ? code(exercise.routes[0].keys) : "")
        || rejection(exercise.rejectedRoutes?.[0]),
    ])));
    lines.push("");
  }

  const uncovered = exercises.filter(exercise => exercise.canonicalCovered === false && ["none-shorter", "inconclusive"].includes(exercise.verdict));
  if (uncovered.length) {
    lines.push("## Canonicals outside the search grammar", "", "Their verdicts speak only for the routes the grammar covers.", "");
    lines.push(table(["Unit", "Exercise", "Verdict", "Taught"], uncovered.map(exercise => [
      String(exercise.unitNumber), exercise.id, exercise.verdict, code(exercise.canonical.keys),
    ])));
    lines.push("");
  }

  const counted = exercises.filter(exercise => exercise.counted?.length && exercise.verdict !== "shorter");
  if (counted.length) {
    lines.push("## Counted routes", "", `Routes that win only with a count of ${report.countedFrom} or more.`, "");
    lines.push(table(["Unit", "Exercise", "Keys", "Counted route", "Keys"], counted.map(exercise => [
      String(exercise.unitNumber), exercise.id, String(exercise.canonical.cost), code(exercise.counted[0].keys), String(exercise.counted[0].cost),
    ])));
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}
